[build]
  command = "pip install -r requirements.txt && python setup.py install"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 